import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useSession, signIn, signOut } from "next-auth/react"

const Nav = () => {
const { data: session } = useSession()

return (
<>

  <Head>
    <title>Forge ▪ DeFi Bootcamp</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/images/favicon.png" />
  </Head>

  <div className="navbar bg-[#0d0e0e] md:px-10">
    <div className="navbar-start">
      <div className="dropdown">
        <label tabIndex={0} className="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </label>
        <ul tabIndex={0} className="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li><a>Item 1</a></li>
          <li tabIndex={0}>
            <a className="justify-between">
              Parent
              <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24">
                <path d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>
            </a>
            <ul className="p-2">
              <li><a>Submenu 1</a></li>
              <li><a>Submenu 2</a></li>
            </ul>
          </li>
          <li><a>Item 3</a></li>
        </ul>
      </div>
      <Link href="/" passHref>
      <a className="flex justify-center items-center">
        <Image alt="ForgeDEX" height={44} src="https://testnet.forge.trade/images/ForgeIcon.png" width={44} />
      </a>
      </Link>
      <a className="ml-2 normal-case text-2xl font-extrabold">FORGE BOOTCAMP</a>
    </div>
    <div className="navbar-center hidden lg:flex">
      <ul className="menu menu-horizontal px-1">
        <li><a>Item 1</a></li>
        <li tabIndex={0}>
          <a>
            Parent
            <svg className="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
              <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" /></svg>
          </a>
          <ul className="p-2">
            <li><a>Submenu 1</a></li>
            <li><a>Submenu 2</a></li>
          </ul>
        </li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
    <div className="navbar-end">
      {session ? (
      <div className='text-slate-300'>
        Signed in as {session.user?.email} <br />
        <button className='underline' onClick={()=> signOut()}>Sign out</button>
      </div>
      ) : (
      <p>
        <button onClick={()=> signIn()}>Sign in with GitHub</button>
      </p>
      )}
      <a className="btn">Get started</a>
    </div>
  </div>

</>
)
}

export default Nav;