import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useSession, signIn, signOut } from "next-auth/react"

const Nav = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Forge – Get the most out of your liquidity.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='h-[96px] py-4 px-8 mb-0 flex items-center justify-between space-x-3 bg-[#0d0e0e]'>
        <div className='flex justify-center'>
          <Link href="/" passHref>
            <a className="flex justify-center items-center">
              <Image
                alt="ForgeDEX"
                height={50}
                src="https://testnet.forge.trade/images/ForgeIcon.png"
                width={50}
              />
              <span className="inline-block ml-3 font-medium truncate text-slate-300">
                Forge | DeFi Academy
              </span>
            </a>
          </Link>
        </div>
        <div className='text-right text-sm'>
          {session ? (
            <div className='text-slate-300'>
              Signed in as {session.user?.email} <br />
              <button className='underline' onClick={() => signOut()}>Sign out</button>
            </div>
          ) : (
            <p>
              <button onClick={() => signIn()}>Sign in with GitHub</button>
            </p>
          )}
        </div>
      </nav>
    </>
  )
}

export default Nav;
